### ISSUE TITLE
Losing access to window functions

### ISSUE THREAD

**Issue by cleiltonoliveira** [rebrowser/rebrowser-patches#13]
Good job man, it really works in most cases, I did some local tests and it seems that the code is more resilient to the recaptcha service now.

However, I noticed that by applying the patch I am losing access to some functions through the browser window object, I believe it is because of the patch's context isolation, do you have any suggestions about this?

I can't run things like this:
```
await page.waitForFunction(
        `typeof window.grecaptcha !== 'undefined' && typeof window.grecaptcha.enterprise.execute === 'function'
         || typeof window.grecaptcha.execute === 'function'`
       ); 
```

**Comment by RealMrHex** [comment]
any solution?

**Comment by nwebson** [comment]
I have some workaround working quite good, I'm working on making a blog post to cover this issue.
Please stay tuned.

**Comment by ottodriver** [comment]
@cleiltonoliveira  what kind of improvement are you seeing with recaptcha?, I'm bypassing recaptcha at 70% rate without this patch, just with residential proxies + stealth.

**Comment by RealMrHex** [comment]
@ottodriver do u have any solution for datadome slider captcha?

**Comment by RealMrHex** [comment]
@nwebson browser still trigger the data-dome captcha when i open the website even when i use `connect` and residential proxies. any idea?

**Comment by nwebson** [comment]
@RealMrHex please share your code

**Comment by cleiltonoliveira** [comment]
> @cleiltonoliveira what kind of improvement are you seeing with recaptcha?, I'm bypassing recaptcha at 70% rate without this patch, just with residential proxies + stealth.

I'm not sure what happened exactly, maybe there could be some other issue in my code that the patch covers, I don't have metrics on that yet, but I'm sure without the patch my bot is easier to be detect.

**Comment by cleiltonoliveira** [comment]
@ottodriver About proxies, I noticed that good proxy providers also have a better rate, have you tried IPv6 proxies?

**Comment by anyaven** [comment]
@nwebson Could you provide the details regarding the workaround?

The [docs](https://github.com/rebrowser/rebrowser-patches?tab=readme-ov-file#2-call-runtimeenable-and-then-immediately-call-runtimedisable) mention that you can use `REBROWSER_PATCHES_RUNTIME_FIX_MODE=enableDisable` to get full access to the main context while still running in a mostly isolated context, but it doesn't seem to work. `window.grecaptcha` is still be undefined.

It's also possible to run the Recaptcha Enterprise scripts (enterprise.js and recaptcha__en.js) manually in the isolated context. That makes `window.grecaptcha` field available to use, but from my tests it seems the resulting token will have a low score, possibly due to the scripts being called twice. Once by the page in the main context and again by me in the isolated context.

Perhaps it's possible to disable javascript to prevent recaptcha scripts running on page load and then run them manually?

**Comment by nwebson** [comment]
📣 I just made a post how to access main world objects from isolated context, please read it here: [How to Access Main Context Objects from Isolated Context in Puppeteer & Playwright](https://rebrowser.net/blog/how-to-access-main-context-objects-from-isolated-context-in-puppeteer-and-playwright-23741)

ℹ️ TLDR: use `page.evaluateOnNewDocument` to listen for window messages and eval code, use `page.evaluate` to send window message with your payload and get response from the main world.
It worked just fine for several clients of mine, please let me know (discord or here) if it doesn't work for you.
