### ISSUE TITLE
browserless

### ISSUE THREAD

**Issue by masylum** [rebrowser/rebrowser-patches#25]
Some of us are using https://github.com/browserless/browserless docker image to separate the headless browser from the consumer. I tried adding `RUN npx rebrowser-patches@latest patch` to both the browserless image and my own image where I run puppeeter-core, but it doesn't seem to work. Any clue how to make it work? Thanks in advance!

**Comment by nwebson** [comment]
It seems like it's just exposing some port for CDP connection that could be used then in puppeteer or playwright, so you can just use `rebrowser-puppeteer` instead of `puppeteer` in your code, and provide the URL to browserless docker.
If it doesn't work for you, please share your code, so I can reproduce.
