### ISSUE TITLE
Crash on FrameManager.#onFrameNavigated()

### ISSUE THREAD

**Issue by mmatferneu** [rebrowser/rebrowser-patches#65]
sometimes (probably because of ads doing shenanigans in the page) the `frameId` is not in the frame tree. When that happens inside `FrameManager.#onFrameNavigated()`, the call to `_frameTree.getById()` will fail,  the `frame` becomes undefined  and the code will crash when it reaches here

https://github.com/rebrowser/rebrowser-puppeteer-core/blob/d1579ee8f34293503dddbbda837fc5ae786fb2bc/src/cdp/FrameManager.ts#L496

Seems to happen quite often, but I wasn't able to create a 100% fool proof reproduction to post here. I think it is because it depends on what ad the page decides to load. Also, and this might be related, I'm not sure why, but very often it seems that an ad gets loaded into a new tab, as if my code had clicked on it. But my code never clicks on anything. It just does 

```
for(const url of urlList)
{
    await  page.goto(url);
    // extract all links
}
```
the crash always happens during one of the `goto` calls. After the first one. It never seems to happen during the first one.

**Comment by MaxLiebsch** [comment]
Dear,
in general I would avoid a for loop for opening pages. Pages can have insanely long loading times and even so everything should be async. You never know what all can go wrong in the process. A node process catch all and error recovery is a must. 

For queue handling I would suggest a solution where you use something like [https://www.npmjs.com/package/p-queue](PQueue) or [https://www.npmjs.com/package/puppeteer-cluster](Puppeteer Cluster) or you build a proper queue yourself.

- you need to handle **errors** properly since they can always arise in the browser or in the involved libraries
- you need to make sure that the amount of open pages is not exceeding the limits of what your machine can handle. **Keyword: Concurrency**
- catch timeouts when they arise, set the waitFor in the goto

I hope that helps. Happy coding.

**Comment by MaxLiebsch** [comment]
You are right you won't catch those with try catch block since it is throw outside the scope of your function.
That's why I suggested process catch all and handling. Probably I was not clear enough on that point.

```
process.on("uncaughtException".... 
```

It might feel like a hack but with puppeteer you will have these exceptions that bubble up in the event loop. If you find a better way let me know. 

As for your initial question., do you have more code to spare and a page where it occurs otherwise might be difficult to spot any issue from your text only.

**Comment by jxhczhl** [comment]
Adding a check before "frame.worlds" on line 496 of FrameManager.ts, changing it to "frame && frame.worlds," should work. I've already manually modified the source code, and the issue hasn't occurred since.

**Comment by nwebson** [comment]
Thanks for reporting this bug, just fixed it in the new release: 
https://github.com/rebrowser/rebrowser-patches/releases/tag/1.0.17

**Comment by AndriusCTR** [comment]
Noticed exactly the same issue, periodically. Thanks for fix.
